global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
  - job_name: 'risk-analytics'
    static_configs:
      - targets: ['risk-analytics:9096']
